Update filter-proxies.yml

diff --git a/.github/workflows/filter-proxies.yml b/.github/workflows/filter-proxies.yml
--- a/.github/workflows/filter-proxies.yml
+++ b/.github/workflows/filter-proxies.yml
@@ -19,10 +19,15 @@ jobs:
     
     - run: python filter_proxies.py
     
-    - name: Commit and push if files exist
+    - name: Commit and push if file exists
       run: |
-        git config user.name "GitHub Actions"
-        git config user.email "actions@github.com"
-        git add BLACK_VLESS_RUS_FILTERED.txt WHITE_LIST_FILTERED.txt
-        git diff --staged --quiet || git commit -m "Update filtered proxies (black + white)"
-        git push
+        if [ -f BLACK_VLESS_RUS_FILTERED.txt ]; then
+          git config user.name "GitHub Actions"
+          git config user.email "actions@github.com"
+          git add BLACK_VLESS_RUS_FILTERED.txt
+          git diff --staged --quiet || git commit -m "Update filtered proxies"
+          git push
+        else
+          echo "Error: BLACK_VLESS_RUS_FILTERED.txt was not created"
+          exit 1
+        fi
